version: '3.1'

services:

  db:
    container_name: oracle
    image: oraclelinux:${ORACLE_VERSION}
    restart: always
    tty: true
    environment:
      ORACLE_ALLOW_REMOTE: true
      ORACLE_EDITION: developer
      INIT_SGA_SIZE: 2000
      INIT_PGA_SIZE: 500
      ENABLE_ARCHIVELOG: false
      ORACLE_SID: ${ORACLE_SID}
      ORACLE_PDB: ${ORACLE_PDB}
      ORACLE_PWD: ${ORACLE_PWD}
    volumes:
        - ./oracle-data:/opt/oracle/oradata
        - ./oracle-backup:/opt/oracle/backup
    ports:
      - "1521:1521"
    # For Podman
    privileged: true
volumes:
  oracle-data:
  oracle-backup:
