version: '3.1'

services:

  db:
    container_name: postgres-sql
    image: postgres:${POSTGRESQL_VERSION}
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      PGDATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    volumes:
        - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db-data: