version: '3.1'

services:

  db:
    container_name: postgres-sql
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      PGDATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: 'admin'
    volumes:
        - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db-data: